#!/usr/bin/env bash
# wave.sh - simulate a problem, then open its waveforms in GTKWave
#
# Usage:  ./wave.sh [problem-dir] [--no-gui]     e.g.  ./wave.sh problem1
#         cd problem1 && ../wave.sh            (defaults to the current dir)
#
# VCD_FILE / GTKW_SAVE come from the problem's problem.env. If WAVES is
# defined there, the .gtkw layout is (re)generated from it on every run
# (see problem1/problem.env for the syntax; display formats are hex, dec,
# bin, oct and ascii). Otherwise a pre-made
# GTKW_SAVE file is used if it exists (save over it from gtkwave's File
# menu to keep your own layout).
#
# --no-gui runs the simulation and (re)generates the .gtkw but does not
# launch gtkwave (useful for testing or headless shells).
#
# Before viewing, the VCD is converted to a compressed FST next to it
# (vcd2fst --compress) - gtkwave loads FST much faster than VCD. If vcd2fst
# is not available the raw VCD is opened instead.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

NO_GUI=0
ARGS=()
for a in "$@"; do
  case "$a" in
  --no-gui) NO_GUI=1 ;;
  *) ARGS+=("$a") ;;
  esac
done

# resolve the problem directory (argument or current directory)
PROBLEM_DIR="$(cd "${ARGS[0]:-.}" 2>/dev/null && pwd)" || {
  echo "error: problem directory '${ARGS[0]:-.}' does not exist" >&2
  exit 1
}

ENV_FILE="$PROBLEM_DIR/problem.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "error: $ENV_FILE not found (see problem1/ for a template)" >&2
  exit 1
fi
# shellcheck disable=SC1090
source "$ENV_FILE"

: "${VCD_FILE:?problem.env must define VCD_FILE}"

# run the simulation (re)generating the VCD
"$REPO_ROOT/sim.sh" "$PROBLEM_DIR"

VCD="$PROBLEM_DIR/$VCD_FILE"
GTKW="$PROBLEM_DIR/${GTKW_SAVE:-}"

if [ ! -s "$VCD" ]; then
  echo "error: $VCD was not produced - does \$dumpfile in the testbench match VCD_FILE?" >&2
  exit 1
fi

# ----------------------------------------------------------------------
# convert the VCD to a compressed FST (gtkwave loads FST much faster)
# ----------------------------------------------------------------------
WAVE="$VCD"
if command -v vcd2fst >/dev/null 2>&1; then
  FST="${VCD%.vcd}.fst"
  echo "==> vcd2fst --compress ${VCD#"$REPO_ROOT"/} ${FST#"$REPO_ROOT"/}"
  vcd2fst --compress "$VCD" "$FST"
  WAVE="$FST"
else
  echo "note: vcd2fst not found - opening the uncompressed VCD" >&2
fi

# ----------------------------------------------------------------------
# generate the .gtkw layout from WAVES (if the problem defines it)
# ----------------------------------------------------------------------
if [ -n "${WAVES:-}" ]; then
  : "${TB_TOP:?problem.env must define TB_TOP when WAVES is used}"
  GTKW="$PROBLEM_DIR/${GTKW_SAVE:-sim/$TB_TOP.gtkw}"
  mkdir -p "$(dirname "$GTKW")"

  {
    echo '[*]'
    echo '[*] GTKWave Analyzer v3.3.104 (w)1999-2020 BSI'
    echo '[*] generated by wave.sh from WAVES in problem.env - do not edit'
    echo '[timestart] 0'
    echo '[size] 1400 900'
    echo '[pos] -1 -1'
    echo '*-2.000000 0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1'
    echo "[treeopen] $TB_TOP."
    # pre-expand the SST tree at each scope that contains a listed wave
    for w in $WAVES; do
      n="${w%%|*}"  # strip |fmt suffix
      n="${n%%\[*}" # strip [msb:lsb] suffix
      case "$n" in
      *.*) echo "${n%.*}" ;; # innermost scope of the wave
      esac
    done | sort -u | while read -r scope; do
      echo "[treeopen] $TB_TOP.$scope."
    done
    echo '[sst_width] 233'
    echo '[signals_width] 240'
    echo '[sst_expanded] 1'

    # signal list; the @-flag is sticky, so re-emit it whenever the
    # radix changes (and after every blank separator row)
    fmt_prev=''
    for w in $WAVES; do
      if [ "$w" = '-' ]; then
        echo '@200' # marker for a blank/comment row
        echo '-'
        fmt_prev='@200'
        continue
      fi
      case "$w" in
      *\|*)
        name="${w%%|*}"
        fmt="${w##*|}"
        ;;
      *)
        name="$w"
        fmt='hex'
        ;;
      esac
      # GTKWave trace flags are a hex bitmask: 0x20 right-justifies the
      # signal name, and the data format is OR'd in as a bit:
      #   hex=0x02  dec=0x04  bin=0x08  oct=0x10  ascii=0x800
      case "$fmt" in
      hex) flag='@22' ;;
      dec) flag='@24' ;;
      bin) flag='@28' ;;
      oct) flag='@30' ;;
      ascii) flag='@820' ;;
      *)
        echo "error: unknown wave format '$fmt' in WAVES entry '$w'" >&2
        echo "       (use hex, dec, bin, oct or ascii)" >&2
        exit 1
        ;;
      esac
      if [ "$flag" != "$fmt_prev" ]; then
        echo "$flag"
        fmt_prev="$flag"
      fi
      echo "$TB_TOP.$name"
    done
  } >"$GTKW"

  echo "==> generated ${GTKW#"$REPO_ROOT"/} from WAVES"
fi

if [ "$NO_GUI" -eq 1 ]; then
  exit 0
fi

if ! command -v gtkwave >/dev/null 2>&1; then
  echo "gtkwave not found in PATH."
  echo "  enter the dev shell first:  nix develop"
  echo "  then view manually:         gtkwave $WAVE"
  exit 0
fi

if [ -f "$GTKW" ]; then
  gtkwave "$WAVE" "$GTKW" &
else
  gtkwave "$WAVE" &
fi
